### ISSUE TITLE
process for making the multi-view hand dataset ready

### ISSUE THREAD

**Issue by monajalal** [pmkalshetti/object_detection#1]
Hey how is the process for cleaning and setting up the multiview hand dataset? Is write_data_to_TFRecords.py also supposed to work for hand dataset?
Also, there is nothing here:
http://bit.ly/2wdYIL1
Can you please share it via email?

**Comment by pmkalshetti** [comment]
The multiview hand dataset itself contains code for obtaining bounding boxes. 

object_detection/notebooks/hand/write_data_to_TFRecord_eager_multiview.ipynb may provide ideas for reading the above obtained bounding boxes and convert them to tfrecords. 

Sorry about the link, the checkpoint files had to be moved to other location. Meanwhile, partially trained checkpoints have been provided at the same location.
